### PR TITLE
Support for Android URIs,  Complete Migration to V2, Project update and cleanup

### PR DESCRIPTION
**Pull request by chaudharydeepanshu**
* Support for using Android URIs also in `path` of `PdfImageRendererPdf()` method.
* Complete Migration to Android V2 of plugin and example.
* AGP updated to 7.3.0
* Updated required Flutter SDK version to 1.17.0 from 2.0.0.
* Replaced deprecated effective dart with flutter_lints: ^2.0.1
* Fixed all dart analysis issues and cleanup

### CODE REVIEW

**Review by p-kuen — APPROVED** [review]
Lgtm

**Comment by chaudharydeepanshu** [comment]
Thanks. 
Also, I have lowered back the minimum required Flutter SDK version to 1.17.0 and the minimum required Dart SDK version back to 2.12.0 as I found the SDK upgrade was kind of unnecessary.

**Comment by d-kuen** [comment]
Tanks for the PR.

Tests worked on my end.

I noticed following points:
- The updated pubspec.lock files are missing, due to the https://github.com/cloudacy/pdf_image_renderer/pull/3/commits/6aae92994066ffe2d892250b949230a0a7b444e2 change. Can you please add the pubspec.lock changes to this PR?
- I think changes in `android/src/main/kotlin/io/cloudacy/pdf_image_renderer/PdfImageRendererPlugin.kt` would be more readable, if the indentation would be changed back to 2 spaces. We could change the indentation in a separate commit/PR.

**Comment by chaudharydeepanshu** [comment]
@d-kuen

> The updated pubspec.lock files are missing, due to the https://github.com/cloudacy/pdf_image_renderer/commit/6aae92994066ffe2d892250b949230a0a7b444e2 change. Can you please add the pubspec.lock changes to this PR?

Sorry If I'm incorrect, please correct me, but I believe you are referring to the downgraded flutter and dart SDK. If so, I purposefully downgraded the SDKs in the https://github.com/cloudacy/pdf_image_renderer/commit/6aae92994066ffe2d892250b949230a0a7b444e2 change as the SDKs upgrade made in the previous commits was not necessary.  After which I did update `pubspec.lock` via pub get. I also mentioned the same in my previous comment. Sorry for the downgrade mess.

> I think changes in android/src/main/kotlin/io/cloudacy/pdf_image_renderer/PdfImageRendererPlugin.kt would be more readable, if the indentation would be changed back to 2 spaces. We could change the indentation in a separate commit/PR.

That's totally fine I can change the indentation back to 2 spaces in a new pr.

**Comment by d-kuen** [comment]
Oh, sorry, I missed the pubpec.lock change. Thanks for the note.

Let's leave the indentation as it is, since there is no additional commit required.

**Pull request merged**
